//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxFWPFClient.JavaCxFReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://hwWebServiceCXF.com/", ConfigurationName="JavaCxFReference.HelloWorld")]
    public interface HelloWorld {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        CxFWPFClient.JavaCxFReference.sayHiResponse sayHi(CxFWPFClient.JavaCxFReference.sayHi request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CxFWPFClient.JavaCxFReference.sayHiResponse> sayHiAsync(CxFWPFClient.JavaCxFReference.sayHi request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://hwWebServiceCXF.com/)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CxFWPFClient.JavaCxFReference.addMyTwoNumbersResponse addMyTwoNumbers(CxFWPFClient.JavaCxFReference.addMyTwoNumbers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CxFWPFClient.JavaCxFReference.addMyTwoNumbersResponse> addMyTwoNumbersAsync(CxFWPFClient.JavaCxFReference.addMyTwoNumbers request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHi {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHi", Namespace="http://hwWebServiceCXF.com/", Order=0)]
        public CxFWPFClient.JavaCxFReference.sayHiBody Body;
        
        public sayHi() {
        }
        
        public sayHi(CxFWPFClient.JavaCxFReference.sayHiBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sayHiBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public sayHiBody() {
        }
        
        public sayHiBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHiResponse", Namespace="http://hwWebServiceCXF.com/", Order=0)]
        public CxFWPFClient.JavaCxFReference.sayHiResponseBody Body;
        
        public sayHiResponse() {
        }
        
        public sayHiResponse(CxFWPFClient.JavaCxFReference.sayHiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sayHiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sayHiResponseBody() {
        }
        
        public sayHiResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMyTwoNumbers", WrapperNamespace="http://hwWebServiceCXF.com/", IsWrapped=true)]
    public partial class addMyTwoNumbers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public addMyTwoNumbers() {
        }
        
        public addMyTwoNumbers(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addMyTwoNumbersResponse", WrapperNamespace="http://hwWebServiceCXF.com/", IsWrapped=true)]
    public partial class addMyTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public addMyTwoNumbersResponse() {
        }
        
        public addMyTwoNumbersResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : CxFWPFClient.JavaCxFReference.HelloWorld, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<CxFWPFClient.JavaCxFReference.HelloWorld>, CxFWPFClient.JavaCxFReference.HelloWorld {
        
        public HelloWorldClient() {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CxFWPFClient.JavaCxFReference.sayHiResponse CxFWPFClient.JavaCxFReference.HelloWorld.sayHi(CxFWPFClient.JavaCxFReference.sayHi request) {
            return base.Channel.sayHi(request);
        }
        
        public string sayHi(string arg0) {
            CxFWPFClient.JavaCxFReference.sayHi inValue = new CxFWPFClient.JavaCxFReference.sayHi();
            inValue.Body = new CxFWPFClient.JavaCxFReference.sayHiBody();
            inValue.Body.arg0 = arg0;
            CxFWPFClient.JavaCxFReference.sayHiResponse retVal = ((CxFWPFClient.JavaCxFReference.HelloWorld)(this)).sayHi(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CxFWPFClient.JavaCxFReference.sayHiResponse> CxFWPFClient.JavaCxFReference.HelloWorld.sayHiAsync(CxFWPFClient.JavaCxFReference.sayHi request) {
            return base.Channel.sayHiAsync(request);
        }
        
        public System.Threading.Tasks.Task<CxFWPFClient.JavaCxFReference.sayHiResponse> sayHiAsync(string arg0) {
            CxFWPFClient.JavaCxFReference.sayHi inValue = new CxFWPFClient.JavaCxFReference.sayHi();
            inValue.Body = new CxFWPFClient.JavaCxFReference.sayHiBody();
            inValue.Body.arg0 = arg0;
            return ((CxFWPFClient.JavaCxFReference.HelloWorld)(this)).sayHiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CxFWPFClient.JavaCxFReference.addMyTwoNumbersResponse CxFWPFClient.JavaCxFReference.HelloWorld.addMyTwoNumbers(CxFWPFClient.JavaCxFReference.addMyTwoNumbers request) {
            return base.Channel.addMyTwoNumbers(request);
        }
        
        public int addMyTwoNumbers(int arg0, int arg1) {
            CxFWPFClient.JavaCxFReference.addMyTwoNumbers inValue = new CxFWPFClient.JavaCxFReference.addMyTwoNumbers();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CxFWPFClient.JavaCxFReference.addMyTwoNumbersResponse retVal = ((CxFWPFClient.JavaCxFReference.HelloWorld)(this)).addMyTwoNumbers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CxFWPFClient.JavaCxFReference.addMyTwoNumbersResponse> CxFWPFClient.JavaCxFReference.HelloWorld.addMyTwoNumbersAsync(CxFWPFClient.JavaCxFReference.addMyTwoNumbers request) {
            return base.Channel.addMyTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CxFWPFClient.JavaCxFReference.addMyTwoNumbersResponse> addMyTwoNumbersAsync(int arg0, int arg1) {
            CxFWPFClient.JavaCxFReference.addMyTwoNumbers inValue = new CxFWPFClient.JavaCxFReference.addMyTwoNumbers();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CxFWPFClient.JavaCxFReference.HelloWorld)(this)).addMyTwoNumbersAsync(inValue);
        }
    }
}
